# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-18 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientmgr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='created',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='created',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='modified',
        ),
        migrations.AlterField(
            model_name='client',
            name='addressLine1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='client',
            name='addressLine2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 2'),
        ),
        migrations.AlterField(
            model_name='client',
            name='addressLine3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 3'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='addressLine1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='addressLine2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 2'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='addressLine3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 3'),
        ),
    ]
