# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-29 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientmgr', '0002_auto_20160519_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='slug',
            field=models.SlugField(default='abc'),
        ),
        migrations.AlterField(
            model_name='client',
            name='clientID',
            field=models.CharField(max_length=254, unique=True, verbose_name='Client Name'),
        ),
    ]
