# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('client_name', models.CharField(max_length=254, verbose_name='Client Name')),
                ('attachment_file', models.FileField(upload_to='oder_soa')),
                ('is_submit', models.BooleanField(default=False, verbose_name='Is submit?')),
                ('is_complete', models.BooleanField(default=False, verbose_name='Is completed?')),
            ],
            options={
                'verbose_name': 'Order SOA',
                'verbose_name_plural': 'Order SOA',
            },
        ),
    ]
