# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('soamgr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewOrderAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Is Approved?')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('soa_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soamgr.OrderSoa')),
            ],
            options={
                'verbose_name': 'Review Order Agreement',
                'verbose_name_plural': 'Review Order Agreement',
            },
        ),
        migrations.CreateModel(
            name='SoaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('type_name', models.CharField(max_length=254, verbose_name='Type Name')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='revieworderagreement',
            name='soa_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soamgr.SoaType'),
        ),
    ]
