# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soamgr', '0002_auto_20160412_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='revieworderagreement',
            name='is_submit',
            field=models.BooleanField(default=False, verbose_name='Send for approval?'),
        ),
    ]
