# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-30 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soamgr', '0003_revieworderagreement_is_submit'),
    ]

    operations = [
        migrations.AddField(
            model_name='revieworderagreement',
            name='approval_choice',
            field=models.CharField(blank=True, choices=[('1', 'Approve OA'), ('2', 'Approve OA when changes Made'), ('3', 'OA requires changes')], max_length=1, null=True),
        ),
    ]
