# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-30 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soamgr', '0004_revieworderagreement_approval_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersoa',
            name='is_adviser_approval',
            field=models.BooleanField(default=False, verbose_name='Is Appoved by Adviser?'),
        ),
    ]
