# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-30 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soamgr', '0005_ordersoa_is_adviser_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revieworderagreement',
            name='soa_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soa_order', to='soamgr.OrderSoa'),
        ),
    ]
