# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-30 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soamgr', '0006_auto_20160430_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersoa',
            name='is_adviser_approval',
        ),
    ]
