# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soamgr', '0007_remove_ordersoa_is_adviser_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersoa',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
