# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-09 15:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('soamgr', '0008_ordersoa_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='revieworderagreement',
            name='paraplanner_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='revieworderagreement',
            name='soa_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soa_type', to='soamgr.SoaType'),
        ),
    ]
