# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-18 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soamgr', '0010_client_entity_partner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Entity',
        ),
        migrations.DeleteModel(
            name='Partner',
        ),
    ]
