# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-18 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soamgr', '0011_auto_20160518_1720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revieworderagreement',
            options={'verbose_name': 'Review OA', 'verbose_name_plural': 'Review OAs'},
        ),
    ]
