# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-20 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('soamgr', '0012_auto_20160519_0123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('client_name', models.CharField(max_length=254, verbose_name='Client Name')),
                ('attachment_file', models.FileField(upload_to='order_soa')),
                ('date_created', models.DateField(blank=True, null=True)),
                ('date_due', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('1', 'OA saved'), ('2', 'OA in-progress'), ('3', 'SOA in-progress'), ('4', 'SOA for review'), ('5', 'SOA finished')], max_length=1, null=True)),
                ('is_submit', models.BooleanField(default=False, verbose_name='Is submitted?')),
                ('is_claim', models.BooleanField(default=False, verbose_name='Is claimed?')),
                ('is_complete', models.BooleanField(default=False, verbose_name='Is completed?')),
            ],
            options={
                'verbose_name': 'SOA',
                'verbose_name_plural': 'SOAs',
            },
        ),
        migrations.AlterModelOptions(
            name='revieworderagreement',
            options={'verbose_name': 'Review Soa', 'verbose_name_plural': 'Review Soas'},
        ),
        migrations.AlterModelOptions(
            name='soatype',
            options={'verbose_name': 'Soa Type', 'verbose_name_plural': 'Soa Types'},
        ),
        migrations.AlterField(
            model_name='revieworderagreement',
            name='approval_choice',
            field=models.CharField(blank=True, choices=[('1', 'Approve SOA'), ('2', 'Approve SOA when changes made'), ('3', 'SOA requires changes')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='revieworderagreement',
            name='soa_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soa_order', to='soamgr.Soa'),
        ),
        migrations.DeleteModel(
            name='OrderSoa',
        ),
    ]
