# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-21 06:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('soamgr', '0014_auto_20160521_1336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soa',
            options={'verbose_name': 'Soa', 'verbose_name_plural': 'Soas'},
        ),
        migrations.RemoveField(
            model_name='revieworderagreement',
            name='soa_type',
        ),
        migrations.AddField(
            model_name='soa',
            name='approval_choice',
            field=models.CharField(blank=True, choices=[('1', 'OA Approved'), ('2', 'SOA started'), ('3', 'SOA finished'), ('4', 'SOA reviewed')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='soa',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='soa',
            name='paraplanner_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='soa',
            name='progress',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='soa',
            name='rating',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='soa',
            name='soa_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soa_type', to='soamgr.SoaType'),
        ),
        migrations.AddField(
            model_name='soatype',
            name='description',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='soatype',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
