# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-21 14:27
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soamgr', '0016_auto_20160521_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_name', models.CharField(max_length=254, verbose_name='Goal Name')),
                ('description', models.CharField(blank=True, max_length=254, null=True, verbose_name='Description')),
                ('parent', models.CharField(max_length=254, verbose_name='Parent Strategy')),
                ('sort', models.SmallIntegerField()),
            ],
            options={
                'verbose_name': 'Client Objective',
                'verbose_name_plural': 'Client Objectives',
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strat_name', models.CharField(max_length=254, verbose_name='Strategy Name')),
                ('description', models.CharField(blank=True, max_length=254, null=True, verbose_name='Description')),
                ('parent', models.CharField(max_length=254, verbose_name='Parent Strategy')),
                ('sort', models.SmallIntegerField()),
            ],
            options={
                'verbose_name': 'Soa Strategy',
                'verbose_name_plural': 'Soa Strategies',
            },
        ),
        migrations.RemoveField(
            model_name='revieworderagreement',
            name='paraplanner_approver',
        ),
        migrations.RemoveField(
            model_name='revieworderagreement',
            name='soa_order',
        ),
        migrations.RemoveField(
            model_name='soatype',
            name='created',
        ),
        migrations.RemoveField(
            model_name='soatype',
            name='modified',
        ),
        migrations.AddField(
            model_name='soa',
            name='goals',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soa',
            name='strategies',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soatype',
            name='guaranteed_time',
            field=models.SmallIntegerField(default=72),
        ),
        migrations.AddField(
            model_name='soatype',
            name='paraplanner_cost',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=6),
        ),
        migrations.AddField(
            model_name='soatype',
            name='paraplanner_time',
            field=models.SmallIntegerField(default=24),
        ),
        migrations.AlterField(
            model_name='soatype',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=6),
        ),
        migrations.DeleteModel(
            name='ReviewOrderAgreement',
        ),
    ]
