# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-29 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soamgr', '0018_auto_20160524_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='task_percent',
            field=models.SmallIntegerField(default=10),
        ),
    ]
