# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-18 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formatting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('styleID', models.CharField(max_length=20, verbose_name='StyleSet ID')),
                ('styleName', models.CharField(max_length=50, verbose_name='StyleSet Name')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'StyleSet',
                'verbose_name_plural': 'StyleSets',
            },
        ),
        migrations.CreateModel(
            name='FormattingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('styleID', models.CharField(max_length=20, verbose_name='StyleSet ID')),
                ('title_font', models.CharField(max_length=50, verbose_name='Title Font')),
                ('title_fontsize', models.SmallIntegerField(default=12, verbose_name='Title FontSize')),
                ('title_forecolor', models.CharField(max_length=50, verbose_name='Title ForeColor')),
                ('title_bold', models.BooleanField(default=False, verbose_name='Title Bold')),
                ('title_italic', models.BooleanField(default=False, verbose_name='Title Italic')),
                ('title_alignment', models.CharField(choices=[('L', 'Left'), ('C', 'Center'), ('R', 'Right'), ('J', 'Justified')], default='L', max_length=1, verbose_name='Title Alignment')),
                ('subtitle_font', models.CharField(max_length=50, verbose_name='Subtitle Font')),
                ('subtitle_fontsize', models.SmallIntegerField(default=12, verbose_name='Subtitle FontSize')),
                ('subtitle_forecolor', models.CharField(max_length=50, verbose_name='Subtitle ForeColor')),
                ('subtitle_bold', models.BooleanField(default=False, verbose_name='Subtitle Bold')),
                ('subtitle_italic', models.BooleanField(default=False, verbose_name='Subtitle Italic')),
                ('subtitle_alignment', models.CharField(choices=[('L', 'Left'), ('C', 'Center'), ('R', 'Right'), ('J', 'Justified')], default='L', max_length=1, verbose_name='Subtitle Alignment')),
                ('h1_font', models.CharField(max_length=50, verbose_name='Heading1 Font')),
                ('h1_fontsize', models.SmallIntegerField(default=12, verbose_name='Heading1 FontSize')),
                ('h1_forecolor', models.CharField(max_length=50, verbose_name='Heading1 ForeColor')),
                ('h1_bold', models.BooleanField(default=False, verbose_name='Heading1 Bold')),
                ('h1_italic', models.BooleanField(default=False, verbose_name='Heading1 Italic')),
                ('h1_alignment', models.CharField(choices=[('L', 'Left'), ('C', 'Center'), ('R', 'Right'), ('J', 'Justified')], default='L', max_length=1, verbose_name='Heading1 Alignment')),
                ('h2_font', models.CharField(max_length=50, verbose_name='Heading2 Font')),
                ('h2_fontsize', models.SmallIntegerField(default=12, verbose_name='Heading2 FontSize')),
                ('h2_forecolor', models.CharField(max_length=50, verbose_name='Heading2 ForeColor')),
                ('h2_bold', models.BooleanField(default=False, verbose_name='Heading2 Bold')),
                ('h2_italic', models.BooleanField(default=False, verbose_name='Heading2 Italic')),
                ('h2_alignment', models.CharField(choices=[('L', 'Left'), ('C', 'Center'), ('R', 'Right'), ('J', 'Justified')], default='L', max_length=1, verbose_name='Heading2 Alignment')),
                ('h3_font', models.CharField(max_length=50, verbose_name='Heading3 Font')),
                ('h3_fontsize', models.SmallIntegerField(default=12, verbose_name='Heading3 FontSize')),
                ('h3_forecolor', models.CharField(max_length=50, verbose_name='Heading3 ForeColor')),
                ('h3_bold', models.BooleanField(default=False, verbose_name='Heading3 Bold')),
                ('h3_italic', models.BooleanField(default=False, verbose_name='Heading3 Italic')),
                ('h3_alignment', models.CharField(choices=[('L', 'Left'), ('C', 'Center'), ('R', 'Right'), ('J', 'Justified')], default='L', max_length=1, verbose_name='Heading3 Alignment')),
                ('h4_font', models.CharField(max_length=50, verbose_name='Heading3 Font')),
                ('h4_fontsize', models.SmallIntegerField(default=12, verbose_name='Heading3 FontSize')),
                ('h4_forecolor', models.CharField(max_length=50, verbose_name='Heading3 ForeColor')),
                ('h4_bold', models.BooleanField(default=False, verbose_name='Heading3 Bold')),
                ('h4_italic', models.BooleanField(default=False, verbose_name='Heading3 Italic')),
                ('h4_alignment', models.CharField(choices=[('L', 'Left'), ('C', 'Center'), ('R', 'Right'), ('J', 'Justified')], default='L', max_length=1, verbose_name='Heading3 Alignment')),
                ('h5_font', models.CharField(max_length=50, verbose_name='Heading5 Font')),
                ('h5_fontsize', models.SmallIntegerField(default=12, verbose_name='Heading5 FontSize')),
                ('h5_forecolor', models.CharField(max_length=50, verbose_name='Heading5 ForeColor')),
                ('h5_bold', models.BooleanField(default=False, verbose_name='Heading5 Bold')),
                ('h5_italic', models.BooleanField(default=False, verbose_name='Heading5 Italic')),
                ('h5_alignment', models.CharField(choices=[('L', 'Left'), ('C', 'Center'), ('R', 'Right'), ('J', 'Justified')], default='L', max_length=1, verbose_name='Heading5 Alignment')),
                ('h6_font', models.CharField(max_length=50, verbose_name='Heading6 Font')),
                ('h6_fontsize', models.SmallIntegerField(default=12, verbose_name='Heading6 FontSize')),
                ('h6_forecolor', models.CharField(max_length=50, verbose_name='Heading6 ForeColor')),
                ('h6_bold', models.BooleanField(default=False, verbose_name='Heading6 Bold')),
                ('h6_italic', models.BooleanField(default=False, verbose_name='Heading6 Italic')),
                ('h6_alignment', models.CharField(choices=[('L', 'Left'), ('C', 'Center'), ('R', 'Right'), ('J', 'Justified')], default='L', max_length=1, verbose_name='Heading6 Alignment')),
                ('normal_font', models.CharField(max_length=50, verbose_name='Normal Font')),
                ('normal_fontsize', models.SmallIntegerField(default=12, verbose_name='Normal FontSize')),
                ('normal_forecolor', models.CharField(max_length=50, verbose_name='Normal ForeColor')),
                ('normal_bold', models.BooleanField(default=False, verbose_name='Normal Bold')),
                ('normal_italic', models.BooleanField(default=False, verbose_name='Normal Italic')),
                ('normal_alignment', models.CharField(choices=[('L', 'Left'), ('C', 'Center'), ('R', 'Right'), ('J', 'Justified')], default='L', max_length=1, verbose_name='Normal Alignment')),
            ],
            options={
                'verbose_name': 'StyleSet Detail',
                'verbose_name_plural': 'StyleSet Details',
            },
        ),
        migrations.CreateModel(
            name='Subtemplates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subTempID', models.CharField(max_length=20, verbose_name='Subtemplate ID')),
                ('parentTempID', models.CharField(max_length=20, verbose_name='Parent Template ID')),
                ('subTempName', models.CharField(max_length=50, verbose_name='Subtemplate Name')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('tempType', models.CharField(max_length=50, verbose_name='Template Type')),
                ('isIncluded', models.BooleanField(default=False, verbose_name='Is Included?')),
                ('HasPageBreak', models.BooleanField(default=False, verbose_name='Has Page Break?')),
                ('subTampGdocID', models.CharField(max_length=254, verbose_name='Subtemplate Google Doc ID')),
                ('subTampGdocLink', models.CharField(max_length=254, verbose_name='Subtemplate Google Doc Link')),
                ('parentGdocID', models.CharField(max_length=254, verbose_name='Parent Template Google Doc ID')),
                ('parentGdocLink', models.CharField(max_length=254, verbose_name='Parent Template Google Doc Link')),
            ],
            options={
                'verbose_name': 'Subtemplate',
                'verbose_name_plural': 'Subtemplates',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempID', models.CharField(max_length=20, verbose_name='Template ID')),
                ('tempName', models.CharField(max_length=50, verbose_name='Template Name')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('tempType', models.CharField(max_length=50, verbose_name='Template Type')),
                ('notes', models.CharField(blank=True, max_length=254, null=True, verbose_name='Notes')),
                ('udoxTempCombiner', models.CharField(max_length=254, verbose_name='Ultradox Template Combiner')),
                ('udoxFormatSetter', models.CharField(max_length=254, verbose_name='Ultradox Formatting Setter')),
                ('udoxCleanUp', models.CharField(blank=True, max_length=254, null=True, verbose_name='Ultradox CleanUp Routine')),
                ('udoxDraftUpdater', models.CharField(max_length=254, verbose_name='Ultradox Draft Updater')),
                ('udoxMain', models.CharField(max_length=254, verbose_name='Ultradox Main')),
                ('wksClientData', models.CharField(max_length=254, verbose_name='Client Data Worksheet')),
                ('wksTempData', models.CharField(max_length=254, verbose_name='Template Data Worksheet')),
                ('wksStratData', models.CharField(max_length=254, verbose_name='Strategy Data Worksheet')),
            ],
            options={
                'verbose_name': 'Soa Template',
                'verbose_name_plural': ' Soa Templates',
            },
        ),
    ]
