# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-19 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tempmgr', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtemplates',
            old_name='subTampGdocID',
            new_name='subTempGdocID',
        ),
        migrations.RenameField(
            model_name='subtemplates',
            old_name='subTampGdocLink',
            new_name='subTempGdocLink',
        ),
    ]
