# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-09 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160410_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_name',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Account Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='account_number',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Account Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='bsb',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='BSB'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_paraplanner',
            field=models.BooleanField(default=False, verbose_name='Is Paraplanner?'),
        ),
    ]
